/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java_jna;

import org.junit.Test;

import static org.junit.Assert.*;

public class FilterTest {
    @Test public void testFilter100() throws Exception {
        assertNull(Filter.create("should not exist"));
        Filter filter = Filter.create("i64_gt");
        assertNotNull(filter);
        filter.init("100");
        assertTrue(filter.filter("101"));
        assertFalse(filter.filter("100"));
        assertTrue(filter.filter("1000"));
        assertFalse(filter.filter("-1"));
        filter.destroy();
    }

    @Test public void testFilter5() throws Exception {
        Filter filter = Filter.create("i64_gt");
        assertNotNull(filter);
        filter.init("5");
        assertTrue(filter.filter("100"));
        assertFalse(filter.filter("5"));
        assertTrue(filter.filter("1000"));
        assertFalse(filter.filter("-1"));
        filter.destroy();
    }
}
