/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_demo_Filter */

#ifndef _Included_jni_demo_Filter
#define _Included_jni_demo_Filter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_demo_Filter
 * Method:    create_jni_filter
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_jni_1demo_Filter_create_1jni_1filter
  (JNIEnv *, jclass, jstring);

/*
 * Class:     jni_demo_Filter
 * Method:    init
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jni_1demo_Filter_init
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jni_demo_Filter
 * Method:    filter
 * Signature: (J[B)Z
 */
JNIEXPORT jboolean JNICALL Java_jni_1demo_Filter_filter
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     jni_demo_Filter
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jni_1demo_Filter_destroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
